In [2]:
#dot function

import numpy as np

arr1 = np.array([[1,2],[3,4]])  
arr2 = np.array([[5,6],[7,8]])  
print(np.dot(arr1,arr2))
print(np.vdot(arr1,arr2)) 

[[19 22]
 [43 50]]
70


In [4]:
#Multidot_multiplication
a = np.random.randint(-4,4,(500,5))
b = np.random.randint(-4,4,(5,1000))
c = np.random.randint(-4,4,(1000,10))
z = np.linalg.multi_dot([a,b,c]) 
print(z, '\n')

[[ -783 -2869 -1584 ... -2303 -1872 -2553]
 [  477  1073  1252 ...   583  1740  1381]
 [-1170   112 -1883 ...   114 -4246 -2466]
 ...
 [ -705 -2088 -1065 ...   -75  -717 -1727]
 [  453  1655   -22 ...  -452 -1380   -67]
 [-2755 -3418 -3607 ... -1751 -5877 -4517]] 



In [5]:
z = a.dot(b).dot(c)
print(z, '\n') 

[[ -783 -2869 -1584 ... -2303 -1872 -2553]
 [  477  1073  1252 ...   583  1740  1381]
 [-1170   112 -1883 ...   114 -4246 -2466]
 ...
 [ -705 -2088 -1065 ...   -75  -717 -1727]
 [  453  1655   -22 ...  -452 -1380   -67]
 [-2755 -3418 -3607 ... -1751 -5877 -4517]] 



In [6]:
#inner/outer function 
a = np.array([1,2,3])  
b = np.array([7,8,9]) 
i=np.inner(a,b)
print(i)
o=np.outer(a,b)
print(o)

50
[[ 7  8  9]
 [14 16 18]
 [21 24 27]]


In [7]:
#MatrixMultiplication 
#same shape marices
a = np.array([4,5,6])  
b = np.array([7,8,9])  
i=np.matmul(a,b)
print(i)

122


In [10]:
#determinant
a = np.array(([4,5],[2,3])) 
m=(np.linalg.det(a))
print(m)

2.0


In [2]:
#quadratic equations

import numpy as np
a = np.array([[7,8],[5,6]])  
b = np.array([[1,2],[3,4]])  
s=np.linalg.solve(a, b)
print(s)

[[ -9. -10.]
 [  8.   9.]]


In [3]:
#inverse function
a = np.array([[7,8],[5,6]])
inverse=np.linalg.inv(a)
print(inverse)

[[ 3.  -4. ]
 [-2.5  3.5]]


In [4]:
#trace fn
a = np.array([[1,2],[3,4]])  
print(np.trace(a))

5


In [5]:
#rank
a = np.array([[1,2],[3,4]])  
print(np.linalg.matrix_rank(a))

2


In [2]:
#eigen_value functions
import numpy as np

A = np.array([[1,2,3],[3,2,-1],[4,0,-4]])
val, vect = np.linalg.eig(A)
print("\nEigen values:")
print(val)
print("\nEigen vectors:")
print(vect)


Eigen values:
[-6.05798024  4.4666812   0.59129904]

Eigen vectors:
[[ 0.44047381 -0.66326042  0.49735565]
 [-0.27023519 -0.67962995 -0.75158903]
 [-0.85612836 -0.31335084  0.43330277]]


In [4]:
#linespace and logspace

np.logspace(0, 10, num=4)

array([1.00000000e+00, 2.15443469e+03, 4.64158883e+06, 1.00000000e+10])

In [5]:
np.linspace(0, 10, num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [6]:
#matrix_norm
a= np.arange(12).reshape(4,3)
b = np.linalg.norm(a)
print(a)
print('\n Frobenius Norm of above matrix:')
print(b) 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 Frobenius Norm of above matrix:
22.494443758403985


In [7]:
a = np.arange(12).reshape(4,3)
b = np.linalg.norm(a, axis=0)
print(b)

[11.22497216 12.88409873 14.62873884]


In [8]:
a = np.arange(12).reshape(4,3)
b = np.linalg.norm(a, axis=1)
# dim = 4
print(b)

[ 2.23606798  7.07106781 12.20655562 17.3781472 ]


In [13]:
#Linear_equations
a = np.random.randint(1,10,[4,4])
b= np.array([4,12,1,3])
x= np.linalg.solve(a,b)
print(a)
print(b)
print(x)

[[7 2 5 3]
 [1 2 4 3]
 [3 7 7 6]
 [7 8 1 2]]
[ 4 12  1  3]
[  65. -162. -398.  621.]
