In [1]:
import numpy as np

In [2]:
a= np.array([(1,2,3) , (3,4,5)])
print(a.ndim)

a= np.array([(1,2,3)])
print(a.itemsize)

a= np.array([(1,2,3) , (3,4,5)])
print(a.dtype)

a= np.array([(1,2,3), (3,4,5)])
print(a.size)

a= np.array([(1,2,3), (3,4,5)])
print(a.shape)

2
4
int32
6
(2, 3)


In [3]:
a = np.linspace(1, 2, 5);
print(a)

a= np.array([(1,2,3), (3,4,5)])
print(a.reshape(3,2))

a= np.array([1,2,3])

print(a.max())
print(a.min())
print(a.sum())

[1.   1.25 1.5  1.75 2.  ]
[[1 2]
 [3 3]
 [4 5]]
3
1
6


In [4]:
a= np.array([(1,2,3), (3,4,5)])
print(a[0:, 2])
print(a.sum(axis=0))
print(np.sqrt(a))
print(np.std(a))


[3 5]
[4 6 8]
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [5]:
a= np.array([(1,2,3), (3,4,5)])
b= np.array([(1,2,3), (3,4,5)])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 2  4  6]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]
